[package]
name = "myrust"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
axum = "0.7.5"
etcd-client = "0.14.0"
hmac = "0.12.1"
jwt = "0.16.0"
mac_address = "1.1.7"
paste = "1.0.15"
pin-project = "1.1.5"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
serde_yaml = "0.9.34"
sha2 = "0.10.8"
thiserror = "1.0.63"
tokio = { version = "1.40.0", features = ["rt-multi-thread"] }
toml = "0.8.19"
tower = "0.5.0"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
mime = "0.3.17"
base64 = "0.22.1"
reqwest = "0.12.7"
reqwest-middleware = "0.3.3"
http = "1.1.0"
async-trait = "0.1.82"
