[package]
name = "derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.79", default-features = false }
quote = { version = "1.0.37", default-features = false }
